#!/bin/bash

sudo apt-get install git subversion gcc-avr avr-libc avrdude build-essential ruby libqtcore4  libqt4-dev qt4-qmake g++ cmake libxerces-c-dev xsdcxx libsdl1.2-dev libusb-1.0-0 libphonon-dev phonon libqtwebkit-dev python-qt4 python-qt4-dev
git clone -b 2.1 https://github.com/opentx/opentx
cd opentx/companion
mkdir lbuild
cd lbuild
cmake ../src
make clean
make
sudo make install
