#!/bin/bash

# Define colors...
RED=`tput bold && tput setaf 1`
GREEN=`tput bold && tput setaf 2`
YELLOW=`tput bold && tput setaf 3`
BLUE=`tput bold && tput setaf 4`
NC=`tput sgr0`

function RED(){
	echo -e "\n${RED}${1}${NC}"
}
function GREEN(){
	echo -e "\n${GREEN}${1}${NC}"
}
function YELLOW(){
	echo -e "\n${YELLOW}${1}${NC}"
}
function BLUE(){
	echo -e "\n${BLUE}${1}${NC}"
}

mkdir testbench
cd testbench

BLUE "Cloning Hak5 repositories..."
wget https://wifipineapple.com/wp6.sh
chmod +x wp6.sh
git clone https://github.com/hak5/bashbunny-payloads
git clone https://github.com/hak5darren/USB-Rubber-Ducky

BLUE "Cloning Seclists..."
git clone https://github.com/danielmiessler/SecLists

BLUE "Creating leich..."
git clone https://github.com/rbeaden/leich

