#!/bin/bash

#cat /etc/lsb-release
cat /etc/lsb-release | grep '^DISTRIB_ID' | awk -F=  '{ print $2 }'
dpkg -l | grep 'ubuntu-desktop' | awk -F= '{ print $2 }'

#echo "Install virtualbox?"
#program="virtualbox"
#condition=$(which $program 2>/dev/null | grep -v "not found" | wc -l)
#if [ $condition -eq 0 ] ; then
#	echo "virtualbox not installed, installing....."
#       sudo apt install virtualbox-qt -y
#	echo "installation complete"
#fi


#sudo apt install virtualbox-qt
#which "Betaflight-configurator" 2>/dev/null | grep -v "not found" | wc -l

#Spider site
wget --spider -H -nv -nd -o ~/wget.log -e robots=off -w 1 -r -p http://google.com

grep -Eo '(http|https)://[^/"]+' wget.log | sort -u

#Download Website
wget -mkEpnp
