#!/bin/bash

wget https://github.com/betaflight/betaflight-configurator/releases/download/10.2.0/betaflight-configurator_10.2.0_amd64.deb
sudo dpkg -i betaflight-configurator_10.2.0_amd64.deb
(echo '# DFU (Internal bootloader for STM32 MCUs)'
 echo 'ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", MODE="0664", GROUP="plugdev"') | sudo tee /etc/udev/rules.d/45-stdfu-permissions.rules > /dev/null
sudo usermod -G dialout -a leich

