#!/bin/bash

# See http://steamcommunity.com/app/221410/discussions/0/846940247807787326/
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7

REPO="deb http://repo.steampowered.com/steam/ $(lsb_release -cs) steam"
sudo echo "${REPO}" > /etc/apt/sources.list.d/steam.list

sudo apt-get update

sudo apt-get install -y steam
